\import ArendAST.Definition
\import ArendAST.Expression
\import ArendAST.Level
\import ArendAST.Reduction.Normalize
\import ArendAST.Typecheck.Env
\import Data.Array
\import Data.Bool
\import Data.List (List)
\import Data.Maybe
\import Debug.Meta
\import Function.Meta
\import Monad.Do
\import Utilities.Monad
\import Utilities.Monad.Maybe
\import ArendAST.PreludeFuncs

\func factorial : Definition => DFunc $ \new FuncDef {
  | name => "!"
  | id => 10001
  | params => x :: nil
  | resultSort => Set0
  | resultType => ETNat
  | truncLevel => nothing
  | body => just $ DoMatch $
                   cClause (PZero :: nil) (just $ ENat 1) ::
                   cClause (PSuc (PVar y) :: nil) (just $ EFunCall *NatV nil (
                     ECSuc (EVar y) ::
                     EFunCall factorialV nil (EVar y :: nil) ::
                     nil)) :: nil
  | isSFunc => false
} \where {
  \func x => LocalVar "x" 0 ETNat nothing
  \func y => LocalVar "y" 1 ETNat nothing
}
\func factorialV : Var => GlobalVar "!" 10001 (EPiType (factorial.x :: nil) ETNat Set0) nothing


\func env+* : CheckEnv \cowith
  | vars => -- +NatV :: *NatV ::
                     factorialV :: nil
  | plevels => nil
  | defs => -- +Nat :: *Nat ::
                     factorial :: nil

\func two*two : Expr => EFunCall *NatV nil (ENat 2 :: ENat 2 :: nil)
\func four_test => normalize.normalizeWithFuelR env+* two*two 5
\func four_p => println four_test


\func factorial2 : Expr => EFunCall factorialV nil (ENat 2 :: nil)
\func factorial2_test => normalize.normalizeWithFuelR env+* factorial2 6
\func factorial2_print => println factorial2_test

\func fac2Step : Expr => EFunCall *NatV nil (ENat 2 ::
  ECase false nil ETNat nil  (DoMatch (cClause nil  (just
      (EFunCall *NatV nil (ECSuc (ENat 0) ::
      EFunCall factorialV nil (ENat 0 :: nil) :: nil))) ::
  nil)) nil :: nil)
\func fac2_fin => normalize.normalizeWithFuelR env+* fac2Step 6
\func fac2_p => println fac2_fin
