\import ArendAST.Definition
\import ArendAST.Expression
\import ArendAST.Quote
\import ArendAST.Reduction.CompClosure
\import ArendAST.Typecheck.Typecheck
\import ArendAST.Typecheck.Env
\import Arith.Nat
\import Data.Bool
\import Debug.Meta
\import Meta
\import Utilities.Arith
\import Utilities.Monad.Reader
\import ArendAST.Level
\import Data.Maybe
\import Paths
\import ArendAST.Typecheck.Error

\func typeAs (i : Nat) (t : Expr) (e : Expr) => compClosure step e \where {
  \func step (_ : Expr) : Expr
    | EVar (LocalVar name index type eval) => if (index ==_B i)
        (EVar (LocalVar name index t eval))
        (EVar (LocalVar name index type eval))
    | EVar (GlobalVar name index type eval) => if (index ==_B i)
        (EVar (GlobalVar name index t eval))
        (EVar (GlobalVar name index type eval))
    | t => t
}

\func combK : Expr => quot { (
  (\lam (A : \7-Type 5) (x : A) (_ : A) => x),
  (x$0 : \Prop)
) : \Sigma (u : \Pi (A : \Set0) (x : A) (y : A) -> A) (v : \Type 0)}

\func typecheckK_p => println
    ((typecheck combK).runReaderT
        (extend (GlobalVar "x" 0 (EUniv Prop) nothingE) emptyEnv))

\func str : Expr => quot { "x" }

\func typecheckStr_p => println
  ((typecheck str).runReaderT emptyEnv)

\func useData : Expr => quot { \lam (x : (D$100 : \Set0)) => \case x \as u \return Int \with { | C$101 (y : Int) => y | E$102 => pos 1 } }
\func useData_p => println useData
\func typecheckData_p => println ((typecheck useData).runReaderT
    (extend (GlobalVar "D" 100 (EUniv Set0) nothingE)
        (extendDef (DData (\new DataDef "D" 100 nil Set0 (
          (\new ConsDef "C" 101 100 (LocalVar "y" 3 ETInt nothingE :: nil) nothing nothing) ::
          (\new ConsDef "E" 102 100 nil nothing nothing) :: nil
        ) nothing false)) emptyEnv)))
\func typecheckDataWrong_p => println ((typecheck useData).runReaderT
    (extend (GlobalVar "D" 100 (EUniv Set0) nothingE)
        (extendDef (DData (\new DataDef "D" 100 nil Set0 (
          (\new ConsDef "C" 101 100 (LocalVar "y" 3 ETInt nothingE :: nil) nothing nothing) ::
          (\new ConsDef "E" 103 100 nil nothing nothing) :: nil
        ) nothing false)) emptyEnv)))
\func useData_wrong : Expr => quot { \lam (x : (D$100 : \Set0)) => \case x \as u \return String \with { | C$101 (y : Int) => y | E$102 => pos 1 } }
\func typecheckData_wrong_p => println ((typecheck useData_wrong).runReaderT
    (extend (GlobalVar "D" 100 (EUniv Set0) nothingE)
        (extendDef (DData (\new DataDef "D" 100 nil Set0 (
          (\new ConsDef "C" 101 100 (LocalVar "y" 3 ETInt nothingE :: nil) nothing nothing) ::
          (\new ConsDef "E" 102 100 nil nothing nothing) :: nil
        ) nothing false)) emptyEnv)))
\func finTest : Expr => quot { fromNat {5} 3 : Fin 5 }
\func finTest_p => println ((typecheck finTest).runReaderT emptyEnv)