\import ArendAST.Level
\import Data.Bool
\import Utilities.Monad
\import Data.Maybe

\data Var : \Set0
  | GlobalVar (VName : String) (VId : Nat)   (VType : Expr) (VEvaluation : Maybe Expr)
  | LocalVar  (VName : String) (index : Nat) (VType : Expr) (VEvaluation : Maybe Expr)

\data Expr : \Set0
  -- Atoms
  | EVar Var
  | EInt Int
  | ENat Nat
  | EString String
  | EFin (max : Expr) (fromNat : Expr)

  -- Functions
  | EApp Expr Expr (isExplicit : Bool)
  | ELam (Array Var) Expr (resultSort : Sort)

  -- Tuples
  | ETuple (elements : Array Expr) (type : Expr)
  | EProj Expr Nat (isProperty : Bool)

  -- Calls
  | EFunCall Var (Array PLevel) (Array Expr)
  | EConsCall Var (Array PLevel) (typeArgs : Array Expr) (consArgs : Array Expr)
  | EDataCall Var (Array PLevel) (Array Expr)
  | EFieldCall Var Expr
  | EClassCall Var (Array PLevel) (implementations : Array Var) Sort Var
  -- a Var in implementations is always global, refers to the name of the field, and always carries an evaluation

  -- Records
  | ENew (parent : Maybe Expr) Expr

  -- Arrays
  | EArray (Array PLevel) (elemType : Expr) (elems : Array Expr) (tail : Maybe Expr)

  -- Paths
  | EPath (Array PLevel) Expr Expr
  | EPathAt Expr Expr

  -- Patterns
  | ECase (isSFunc : Bool) (Array Var) (returnType : Expr) (returnLevel : Maybe Expr) Match (args : Array Expr)
  | ELet (isSFunc : Bool) (Array LetClause) (in : Expr)

  -- Wrappers
  | ETyped (value : Expr) (type : Expr)
  | EBox (value : Expr) (type : Expr)
  | EPEval Expr

  -- Types
  | EUniv Sort
  | EPiType (Array Var) Expr Sort
  | ESigmaType (Array Var) Sort
  | ETInt
  | ETNat
  | ETString
  | ETFin Expr
  | EInterval
  | EArrayType (len : Expr) (elemType : Expr)
  -- \type synonym
  | EType (type : Var) (Array PLevel) (clauseNo : Int) (args : Array Expr) (underlying : Expr)
  | ETypeDestr (type : Var) Expr

  -- Errors
  | EError (Maybe Expr)
  | EGoal

\data Match : \Set0
  | NoMatch Expr
  | DoMatch (Array Clause)
  | IntervalMatch (nparams : Nat) (Array (\Sigma (vleft : Maybe Expr) (vright : Maybe Expr))) (fallback : Maybe Match)

\data Clause : \Set0
  | cClause (pats : Array Pattern) (body : Maybe Expr)

\data Pattern : \Set0
  | PVar Var
  | PConstr Var (Array Pattern)
  | PAbsurd

\data LetClause : \Set0
  | cLetClause (name : LetPattern) (body : Expr) (type : Maybe Expr) (isSFunc : Bool)

\data LetPattern : \Set0
  | LPName (name : String) (id : Nat)
  | LPTuple (Array LetPattern)
  | LPRecord (Array (\Sigma (field : Nat) (pat : LetPattern)))

\func ExprSubst : \Set0 => Array (\Sigma Var Expr)