\import Data.Maybe

\data PLevel | PLConst Nat | PLVar Nat {- index into the definition's level params -}
  | PLSuc PLevel | PLMax PLevel PLevel | PLInf

\data HLevel | HLFin Int -- -1 = \Prop, 0 = \Set, k = \k-Type
  | HLInf -- \Type
\record Sort | lp : PLevel | lh : HLevel

\type LevelSubst => Array (\Sigma Nat PLevel)

\func level0 => PLConst 0
\func Prop => \new Sort { | lp => level0 | lh => HLFin -1}
\func Set (l : PLevel) => \new Sort { | lp => l | lh => HLFin 0}
\func Type (l : PLevel) => \new Sort { | lp => l | lh => HLInf}
\func Set0 : Sort => Set level0