\import Arith.Int
\import Data.Maybe

\data LevelType
  | PLevel
  | HLevel

\data LevelVar
  | LP
  | LH
  | NamedLVar LevelType String Int Int
  | InferLVar LevelType

\data Level
  | LMax (v : Maybe LevelVar) (offset : Int) (constant : Int) -- max (v + offset, constant)
  | LInfinity

\record Sort {
  | lp : Level
  | lh : Level
}

\data LevelArgs
  | LArgPair Sort
  | LArgList (Array Level)
  | LArgEmpty

\type LevelSubst => Array (\Sigma LevelVar Level)

\func level0 => LMax nothing 0 0
\func Prop => \new Sort { | lp => level0 | lh => LMax nothing 0 -1}
\func Set (l : Level) => \new Sort { | lp => l | lh => level0}
\func hType (l : Level) => \new Sort { | lp => l | lh => LInfinity}
\func Set0 : Sort => Set level0
\func stdLevel => \new Sort { | lp => LMax (just LP) 0 0 | lh => LMax (just LH) 0 0}

\func succLevel (l : Level) : Level \elim l
  | LInfinity  => LInfinity
  | LMax v o c => LMax v (isuc o) (isuc c)
\func succSort (s : Sort) : Sort => \new Sort { | lp => succLevel s.lp | lh => succLevel s.lh }