\import ArendAST.Expression
\import ArendAST.Level
\import ArendAST.Typecheck.Env
\import Utilities.Monad
\import Utilities.Monad.Reader

\data CheckError
  | ErrUnbound Var
  | ErrNotPi Expr
  | ErrNotSigma Expr
  | ErrNotUniv Expr
  | ErrNotArray Expr
  | ErrInfinityUniverse
  | ErrUnknownType
  | ErrArity Nat Nat                    -- expected spine length, actual
  | ErrBadPattern
  | ErrNonAbsurd
  | ErrLevelParam
  | ErrUnify
  | ErrOutOfFuel
  | ErrIntervalMatch
  | ErrNotAField Var                    -- an implemented field does not belong to the class
  | ErrFieldDuplicate Var               -- a field is implemented more than once
  | ErrFieldMissing Nat                 -- a required field id is not implemented

\data Result.{l} (A : \Set l)
  | ok A
  | err CheckError

\instance ResultMonad.{l} : Monad Result.{l}
  | return a => ok a
  | >>= r f  => \case r \with { | ok a => f a | err e => err e }

\func Env.{l} (A : \Set l) : \Set l => ReaderT CheckEnv Result A
\func throw.{l} {A : \Set l} (e : CheckError) : Env A => liftReader (err {A} e)

\func \infixl 1 >>>.{l} {A B : \Set l} (c1 : Env A) (c2 : Env B) : Env (\Sigma) \cowith
  | runReaderT env => \case c1.runReaderT env \with {
    | ok _ => \case c2.runReaderT env \with {
      | ok _ => ok ()
      | err c => err c
    }
    | err c => err c
  }