\import ArendAST.Expression
\import ArendAST.Level
\import ArendAST.Typecheck.Env
\import Utilities.Monad
\import Utilities.Monad.Reader

\data CheckError
  | ErrUnbound Var
  | ErrNotPi Expr
  | ErrNotSigma Expr
  | ErrNotUniv Expr
  | ErrNotArray Expr
  | ErrInfinityUniverse
  | ErrUnknownType
  | ErrArity Nat Nat                    -- expected spine length, actual
  | ErrBadPattern
  | ErrNonAbsurd
  | ErrLevelParam LevelVar
  | ErrUnify
  | ErrOutOfFuel
  | ErrIntervalMatch
  | ErrNotAField Var                    -- an implemented field does not belong to the class
  | ErrFieldDuplicate Var               -- a field is implemented more than once
  | ErrFieldMissing Nat                 -- a required field id is not implemented

\data Result (A : \Set0)
  | ok A
  | err CheckError

\instance ResultMonad : Monad Result
  | return a => ok a
  | >>= r f  => \case r \with { | ok a => f a | err e => err e }

\func Env (A : \Set0) : \Set0 => ReaderT CheckEnv Result A
\func throw {A : \Set0} (e : CheckError) : Env A => liftReader (err e)

\func \infixl 1 >>> {A B : \Set0} (c1 : Env A) (c2 : Env B) : Env (\Sigma) \cowith
  | runReaderT env => \case c1.runReaderT env \with {
    | ok _ => \case c2.runReaderT env \with {
      | ok _ => ok ()
      | err c => err c
    }
    | err c => err c
  }