\import ArendAST.Definition
\import ArendAST.Expression
\import ArendAST.Level
\import ArendAST.Reduction.Normalize
\import ArendAST.Typecheck.Env
\import ArendAST.Typecheck.Error
\import ArendAST.Typecheck.Unify
\import Arith.Nat
\import Arith.Int
\import Data.Array
\import Data.Bool
\import Data.Fin
\import Data.Maybe
\import Function.Meta
\import Monad.Do
\import Paths.Meta
\import Set
\import Utilities.Array
\import Utilities.Monad
\import Utilities.Monad.Reader
\import Utilities.Arith

\open NatSemiring

\func varType (_ : Var) : Expr
  | GlobalVar _ _ t _ => t
  | LocalVar _ _ t _  => t

\func getVarId (_ : Var) : Nat
  | GlobalVar _ i _ _ => i
  | LocalVar _ i _ _  => i

\func checkIsUniv (_ : Expr) : Env (\Sigma)
  | EUniv _ => return ()
  | EVar (GlobalVar _ _ _ (justE (EUniv _))) => return ()
  | EVar (LocalVar  _ _ _ (justE (EUniv _))) => return ()
  | t => throw (ErrNotUniv t)

\func getSigmaType (_ : Expr) : Maybe (Array Var)
  | ESigmaType vs s => just vs
  | EVar (GlobalVar _ _ _ (justE (ESigmaType vs s))) => just vs
  | EVar (LocalVar  _ _ _ (justE (ESigmaType vs s))) => just vs
  | t => nothing

\func getPiType (_ : Expr) : Maybe (\Sigma (Array Var) Expr Sort)
  | EPiType vs v s => just (vs, v, s)
  | EVar (GlobalVar _ _ _ (justE (EPiType vs v s))) => just (vs, v, s)
  | EVar (LocalVar  _ _ _ (justE (EPiType vs v s))) => just (vs, v, s)
  | t => nothing

\func getArrayType (_ : Expr) : Maybe (\Sigma Expr Expr)
  | EArrayType len elems => just (len, elems)
  | EVar (GlobalVar _ _ _ (justE (EArrayType len elems))) => just (len, elems)
  | EVar (LocalVar _ _ _ (justE (EArrayType len elems))) => just (len, elems)
  | t => nothing

\func projComponentType (vs : Array Var) (body : MaybeExpr) (k i : Nat) : Expr \elim vs, i
  | nil, _       => EGoal
  | v :: _, 0    => varType v
  | v :: vs, suc i => \case body \with {
    | justE e  => projComponentType (substVArray vs v (EProj e k false)) body (suc k) i
    | nothingE => projComponentType vs body (suc k) i
  }

\func fieldInstType (fd : FieldDef) (body : Expr) : Env Expr => \case getPiType fd.type \with {
  | just (ps, cod, s) => return $ spineResult ps cod s (body :: nil)
  | nothing => throw $ ErrNotPi fd.type
}

\func letClauseVar (_ : LetClause) : Env (Array Var)
  | cLetClause name body (justE type) true => letPatternVar type name body (justE body)
  | cLetClause name body (justE type) false => letPatternVar type name body nothingE
  | _ => throw ErrUnknownType \where {
  \func letPatternVar (rtype : Expr) (pat : LetPattern) (bodyR : Expr) (body : MaybeExpr) : Env (Array Var) \elim pat
    | LPName name id => return (GlobalVar name id rtype body :: nil)
    | LPTuple l => \case getSigmaType rtype \with {
      | nothing => throw (ErrNotSigma rtype)
      | just vs => \case vs.len ==_B l.len \with {
        | false => throw (ErrArity vs.len l.len)
        | true => foldIndexM (++) nil l.len (\lam i => letPatternVar (projComponentType vs body 0 i) (l i)
            bodyR (MaybeExpr.map (\lam e => EProj e i false) body))
      }
    }
    | LPRecord l => do {
      \lam env => askT,
      foldIndexM (++) nil l.len (\lam i => \case getDef env (l i).1 \with {
        | just (DField fd) => do {
          \lam instType => fieldInstType fd bodyR,
          letPatternVar instType (l i).2 bodyR
            (MaybeExpr.map (\lam e => EFieldCall (GlobalVar fd.name (l i).1 fd.type nothingE) e) body) }
        | _ => throw ErrUnknownType
      })
    }
}

\func letClausesVars (cs : Array LetClause) : Env (Array Var) \elim cs
  | nil     => return nil
  | c :: cs => do {
    \lam cv => letClauseVar c,
    \lam csv => letClausesVars cs,
    return (cv ++ csv)
  }

\func patternVars (p : Pattern) : Array Var \elim p
  | PVar v            => v :: nil
  | PConstr _ subpats => concatIdx subpats.len (\lam i => patternVars (subpats i))
  | PAbsurd           => nil

\func patternArrayVars (ps : Array Pattern) : Array Var => concatIdx ps.len (\lam i => patternVars (ps i))

\func addEvaluations (_ : Array Var) (_ : Array Expr) : Array Var
  | nil, _ => nil
  | v, nil => v
  | (GlobalVar n i t _ :: vs), (e :: es) => GlobalVar n i t (justE e) :: addEvaluations vs es
  | (LocalVar n i t _ :: vs), (e :: es) => LocalVar n i t (justE e) :: addEvaluations vs es

\func scopeCheck (v : Var) : Env (\Sigma) => do {
  \lam (env : CheckEnv) => askT,
  \case findVar v env.vars \with {
    | false => throw (ErrUnbound v)
    | true => return ()
  }
} \where {
  \func findVar (v : Var) (vs : Array Var) : Bool \elim vs
    | nil => false
    | h :: t => eqVar h v or findVar v t
}

\func expectedArgType (params : Array Var) (args : Array Expr) (i : Nat) : Expr \elim params, args, i
  | nil, _, _              => EGoal
  | v :: _, _, 0           => varType v
  | v :: params, nil, suc i        => expectedArgType params nil i
  | v :: params, a :: args, suc i  => expectedArgType (substVArray params v a) args i


\func spineResult (params : Array Var) (cod : Expr) (s : Sort) (args : Array Expr) : Expr \elim params, args
  | nil, _              => cod
  | params, nil         => EPiType params cod s
  | v :: params, a :: args => spineResult (substVArray params v a) (substitute cod v a) s args

\func substParams (params : Array Var) (body : Expr) (args : Array Expr) : Expr \elim params, args
  | nil, _              => body
  | _, nil              => body
  | v :: params, a :: args => substParams params (substitute body v a) args

\func getCallId (_ : Expr) : Maybe Nat
  | EVar v               => just (getVarId v)
  | EFunCall v _ _       => just (getVarId v)
  | EConsCall v _ _ _    => just (getVarId v)
  | EDataCall v _ _      => just (getVarId v)
  | EFieldCall v _       => just (getVarId v)
  | EClassCall v _ _ _ _ => just (getVarId v)
  | EType v _ _ _ _      => just (getVarId v)
  | ETypeDestr v _       => just (getVarId v)
  | _                    => nothing

\func getCallDef (env : CheckEnv) (e : Expr) : Maybe Definition => \case getCallId e \with {
  | nothing => nothing
  | just id => getDef env id
}

\func consById (cs : Array ConsDef) (cid : Nat) : Maybe ConsDef \elim cs
  | nil     => nothing
  | c :: cs => if (c.id ==_B cid) (just c) (consById cs cid)

\func fieldById (fs : Array FieldDef) (fid : Nat) : Maybe FieldDef \elim fs
  | nil     => nothing
  | f :: fs => if (f.id ==_B fid) (just f) (fieldById fs fid)

\func hasVarId (vs : Array Var) (fid : Nat) : Bool \elim vs
  | nil     => false
  | v :: vs => (getVarId v ==_B fid) or hasVarId vs fid


\func checkFieldsBelong (cls : ClassDef) (impls : Array Var) : Env (\Sigma) =>
  forEachIndexM impls.len (\lam i => \case fieldById cls.fields (getVarId (impls i)) \with {
    | just _  => return ()
    | nothing => throw (ErrNotAField (impls i))
  })

\func checkNoDupFields (impls : Array Var) : Env (\Sigma) \elim impls
  | nil     => return ()
  | v :: vs => \case hasVarId vs (getVarId v) \with {
    | true  => throw (ErrFieldDuplicate v)
    | false => checkNoDupFields vs
  }

-- FUTURE: walk through supers (with some fuel)
\func checkCoverage (cls : ClassDef) (impls : Array Var) : Env (\Sigma) =>
  forEachIndexM cls.fields.len (\lam i => \case hasVarId impls (cls.fields i).id \with {
    | true  => return ()
    | false => throw (ErrFieldMissing (cls.fields i).id)
  })

\func patternToExpr (p : Pattern) : Expr \elim p
  | PVar v            => EVar v
  | PConstr cv subpats => EConsCall cv LArgEmpty nil (mkArray (\lam i => patternToExpr (subpats i)))
  | PAbsurd           => EGoal

\func patIsAbsurd (p : Pattern) : Bool \elim p
  | PVar _            => false
  | PAbsurd           => true
  | PConstr _ subpats => anyIdx subpats.len (\lam i => patIsAbsurd (subpats i))

\func patsAnyAbsurd (ps : Array Pattern) : Bool => anyIdx ps.len (\lam i => patIsAbsurd (ps i))