\import Algebra.Meta
\import ArendAST.Definition
\import ArendAST.Expression
\import ArendAST.Level
\import ArendAST.Typecheck.Env
\import ArendAST.Typecheck.Error
\import ArendAST.Typecheck.ExprGetters
\import Arith.Int
\import Utilities.Arith
\import ArendAST.Typecheck.Unify
\import Arith.Nat
\import Data.Bool
\import Function.Meta
\import Monad.Do
\import Order.LinearOrder
\import Paths.Meta
\import Set
\import Utilities.Array
\import Utilities.Monad
\import Data.Array
\import Data.Maybe
\import Data.Fin
\import Utilities.Monad.Reader
\import ArendAST.Reduction.Normalize
\open Nat

\func typecheck (e : Expr) : Env Expr \elim e
  | EVar v => do {
    scopeCheck v,
    typecheckVar v
  }
  | EInt i => return ETInt
  | EString s => return ETString
  | EApp e1 e2 isExplicit => do {
    \lam te1 => typecheck e1,
    \lam te2 => typecheck e2,
    \case getPiType te1 \with {
      | just (p :: ps, cod, s) => do {
        unify te2 (varType p),
        normalize (spineResult (p :: ps) cod s (e2 :: nil))
      }
      | _ => throw (ErrNotPi te1)
    }
  }
  | ELam a e resultSort => do {
    -- this is probably slower than doing it with lists
    forEachIndexM a.len (\lam i => localT (extendArray (take i a (linarith (fin_< i)))) (typecheckVar (a i))),
    \lam te => localT (extendArray a) (typecheck e),
    -- a lambda's type is the Pi type over its parameters into the body's type
    return (EPiType a te resultSort)
  }
  | ETuple elements e => \case getSigmaType e \with {
    | nothing => throw (ErrNotSigma e)
    | just a => \case decEqNat a.len elements.len \with {
      | no _ => throw (ErrArity a.len elements.len)
      | yes eq => do {
        -- for each element,
        forEachIndexM a.len (\lam i => localT
          -- add the types of elements before it into the context
          (extendArray
            -- with inserted elements as evaluations
            (addEvaluations (take i a (linarith (fin_< i))) (take i elements (linarith (fin_< i))))
          )
          -- and typecheck the next one
          (do {
            \lam t => typecheck (elements (rewriteI eq i)),
            unify t (varType (a i))
          })),
        return e
      }
    }
  }
  | EProj e n isProperty => do {
    \lam te => typecheck e,
    \case getSigmaType te \with {
      | nothing => throw (ErrNotSigma te)
      | just a => \case nat_<=-dec.nat_<=_Bool (suc n) a.len \as x, idp : nat_<=-dec.nat_<=_Bool (suc n) a.len = x \with {
        | true, p => return (varType (nth n a (nat_<-dec {n} {a.len} {So.toSo p})))
        -- TODO this feels wrong, what if the varType has some variables bound earlier in the sigma-type
        | false, _ => throw (ErrArity a.len n)
      }
    }
  }
  | EFunCall v l a => do {
    \lam env => askT,
    \case getDef env (getVarId v) \with {
      | just (DFunc f) => do {
        forEachIndexM a.len (\lam i => do {
          \lam ti => typecheck (a i),
          unify ti (expectedArgType f.params a i)
        }),
        normalize (spineResult f.params f.resultType Set0 a)
      }
      | _ => throw (ErrUnbound v)
    }
  }
  | EConsCall v l typeArgs consArgs => do {
    \lam env => askT,
    \case getDef env (getVarId v) \with {
      | just (DCons c) => \case getDef env c.datatype \with {
        | just (DData d) => do {
          forEachIndexM typeArgs.len (\lam i => do {
            \lam ti => typecheck (typeArgs i),
            unify ti (expectedArgType (d.params ++ c.params) (typeArgs ++ consArgs) i)
          }),
          forEachIndexM consArgs.len (\lam i => do {
            \lam ti => typecheck (consArgs i),
            unify ti (expectedArgType (d.params ++ c.params) (typeArgs ++ consArgs) (typeArgs.len Nat.+ i))
          }),
          normalize (EDataCall (GlobalVar d.name c.datatype (EUniv d.sort) nothingE) l typeArgs)
        }
        | _ => throw (ErrUnbound v)
      }
      | _ => throw (ErrUnbound v)
    }
  }
  | EDataCall v l a => do {
    \lam env => askT,
    \case getDef env (getVarId v) \with {
      | just (DData d) => do {
        forEachIndexM a.len (\lam i => do {
          \lam ti => typecheck (a i),
          unify ti (expectedArgType d.params a i)
        }),
        normalize (spineResult d.params (EUniv d.sort) d.sort a)
      }
      | _ => throw (ErrUnbound v)
    }
  }
  | EFieldCall v e => do {
    \lam env => askT,
    \case getDef env (getVarId v) \with {
      | just (DField fd) => \case getPiType fd.type \with {
        | just (params, cod, s) => do {
          \lam te => typecheck e,
          unify te (expectedArgType params (e :: nil) 0),
          normalize (spineResult params cod s (e :: nil))
        }
        | nothing => throw (ErrNotPi fd.type)
      }
      | _ => throw (ErrUnbound v)
    }
  }
  | EClassCall v l implementations s v1 => do {
    forEachIndexM implementations.len (\lam i => typecheckVar (implementations i)),
    return (EUniv s)
  }
  | ENew parent e => do {
    typecheckMaybe parent,
    typecheck e,
    normalize e
  }
  | EArray l e elems tail => do {
    typecheck e,
    forEachIndexM elems.len (\lam i => do {
      \lam ti => typecheck (elems i),
      \lam eti => normalize (EApp e (EInt (pos i)) true),
      unify ti eti
    }),
    typecheckMaybe tail,
    -- FUTURE: calculate length of tail
    return (EArrayType (\case tail \with { | nothingE => EInt (pos elems.len) | justE _ => EGoal }) e)
  }
  | EPath l e1 e2 => do {
    typecheck e1,
    \lam u => typecheck e2,
    unify e1 u,
    \case getPiType e1 \with {
      | just (i :: as, e, s) => do {
        unify (varType i) EInterval,
        return e1
      }
      | _ => throw (ErrNotPi e1)
    }
  }
  | EPathAt e1 e2 => do {
    \lam tp => typecheck e1,
    \lam ti => typecheck e2,
    unify ti EInterval,
    \case getPiType tp \with {
      | just (params, cod, s) => normalize (spineResult params cod s (e2 :: nil))
      | nothing => throw (ErrNotPi tp)
    }
  }
  | EArrayType len e => do {
    \lam tl => typecheck len,
    unify tl ETInt,
    \lam tf => typecheck e,
    \case getPiType tf \with {
      | just (f :: nil, EUniv s, _) => return (EUniv s) -- FUTURE: unify f with (Fin len)
      | _ => throw (ErrNotPi tf)
    }
  }
  | EInterval => return (EUniv (hType level0))
  | ECase isSFunc params retType returnLevel m args => do {
    forEachIndexM args.len (\lam i => do {
      \lam ti => typecheck (args i),
      unify ti (expectedArgType params args i)
    }),
    forEachIndexM params.len (\lam i => localT (extendArray (take i params (linarith (fin_< i)))) (typecheckVar (params i))),
    localT (extendArray params) (typecheck retType),
    normalize (substParams params retType args)
  }
  | ELet isSFunc clauses e => do {
    forEachIndexM clauses.len (\lam i => typecheckLetClause (clauses i)),
    \lam vars => letClausesVars clauses,
    localT (extendArray vars) (typecheck e)
  }
  | ETyped e t => do {
    \lam te => typecheck e,
    unify te t,
    normalize t
  }
  | EBox e t => do {
    \lam te => typecheck e,
    unify te t,
    normalize t
  }
  | EPEval e => typecheck e
  | EUniv s => \case s.lp \with {
    | LInfinity => throw ErrInfinityUniverse
    | LMax _ _ _ => return (EUniv (succSort s))
  }
  | EPiType params cod s => do {
    forEachIndexM params.len (\lam i => localT (extendArray (take i params (linarith (fin_< i)))) (typecheckVar (params i))),
    localT (extendArray params) (typecheck cod),
    return (EUniv s)
  }
  | ESigmaType params s => do {
    forEachIndexM params.len (\lam i => localT (extendArray (take i params (linarith (fin_< i)))) (typecheckVar (params i))),
    return (EUniv s)
  }
  | EType type l clauseNo args underlying => do {
    typecheck underlying,
    forEachIndexM args.len (\lam i => typecheck (args i)),
    normalize (EFunCall type l args)
  }
  -- TODO resolve type from environment
  | ETypeDestr type e => do {
    typecheckVar type,
    typecheck e,
    return EGoal
  }
  | EError (justE t) => fmapM (\lam e => EError (justE e)) (typecheck t)
  | EError nothingE => return (EError nothingE)
  | EGoal => return EGoal
  | ETInt => return (EUniv Set0)
  | ETString => return (EUniv Set0)


\func typecheckVar (_ : Var) : Env Expr
  | GlobalVar VName VId VType (justE VEvaluation) => do {
    \lam ttype => typecheck VType,
    \lam teval => typecheck VEvaluation,
    unify VType teval,
    checkIsUniv ttype,
    return VType
  }
  | LocalVar VName index VType (justE VEvaluation) => do {
    \lam ttype => typecheck VType,
    \lam teval => typecheck VEvaluation,
    unify VType teval,
    checkIsUniv ttype,
    return VType
  }
  | GlobalVar VName VId VType nothingE => do {
    \lam ttype => typecheck VType,
    checkIsUniv ttype,
    return VType
    }
  | LocalVar VName index VType nothingE => do {
    \lam ttype => typecheck VType,
    checkIsUniv ttype,
    return VType
  }

\func typecheckMaybe (m : MaybeExpr) : Env (\Sigma) \elim m
  | nothingE => return ()
  | justE e  => typecheck e >> return ()

\func typecheckLetClause (c : LetClause) : Env (\Sigma) \elim c
  | cLetClause name body type _ => typecheck body >> typecheckMaybe type