\import Utilities.Monad


\record Reader.{l} (R A : \Set l)
  | runReader : R -> A

\instance ReaderMonad.{l} {R : \Set l} : Monad (Reader R)
  | return a => \new Reader { | runReader => \lam _ => a }
  | >>= x f  => \new Reader { | runReader => \lam r => (f (x.runReader r)).runReader r }

\func ask.{l} {R : \Set l} : Reader R R
  => \new Reader { | runReader => \lam r => r }

\func local.{l} {R A : \Set l} (f : R -> R) (x : Reader R A) : Reader R A
  => \new Reader { | runReader => \lam r => x.runReader (f r)}



\record ReaderT.{l} (R : \Set l) (M : \Set l -> \Set l) (A : \Set l)
  | runReaderT : R -> M A

\instance ReaderTMonad.{l} {R : \Set l} {M : Monad.{l}} : Monad (ReaderT R M)
  | return a => \new ReaderT { | runReaderT => \lam _ => return a }
  | >>= x f  => \new ReaderT { | runReaderT => \lam r => x.runReaderT r >>= \lam a => (f a).runReaderT r }

\func askT.{l} {R : \Set l} {M : Monad.{l}} : ReaderT R M R
  => \new ReaderT { | runReaderT => \lam r => return r }

\func localT.{l} {R : \Set l} {M : Monad.{l}} {A : \Set l} (f : R -> R) (x : ReaderT R M A) : ReaderT R M A
  => \new ReaderT { | runReaderT => \lam r => x.runReaderT (f r) }

\func liftReader.{l} {R : \Set l} {M : Monad.{l}} {A : \Set l} (x : M A) : ReaderT R M A
  => \new ReaderT { | runReaderT => \lam _ => x }